# Cấu hình dành riêng cho môi trường Deploy (Render)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

datn.ai.openai-api-key=${OPENAI_API_KEY}
app.frontend.url=${APP_FRONTEND_URL}
zalopay.redirect-url=${ZALOPAY_REDIRECT_URL}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Tool paths in Linux (Docker)
datn.tool.yt-dlp=/usr/local/bin/yt-dlp
datn.tool.ffmpeg=/usr/bin/ffmpeg
server.port=${PORT:8080}
